In [3]:
!pip install transformers

In [4]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabert")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/637 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/717k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.26M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [5]:
print(tokenizer)

BertTokenizerFast(name_or_path='aubmindlab/bert-base-arabert', vocab_size=64000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	124: AddedToken("+ا", rstrip=False, lstrip=False, single_word=True, normalized=True, special=True),
	125: AddedToken("+ة", rstrip=False, lstrip=False, single_word=True, normalized=True, special=True),
	126: AddedToken("+ت", rstrip=False, lstrip=False, single_word=True, normalized=True, special=True),
	127: AddedToken("+ك", rstrip=False, lstrip=False, single_word=True, normalized=True, special=True),
	128: AddedToken("+ن", rstrip=False, lstrip=False, single_word=True, normalized=True, special=True),
	129: AddedToken("+ه", rstrip=False, lstrip=False, single_word=True, normalized=True, special=True),
	130: AddedToken("+ي", rstrip=False, lstr

In [6]:
tokenizer("السلام عليكم")

{'input_ids': [29756, 445, 44831, 5468, 8155, 29758], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [7]:
tokens=tokenizer.tokenize("السلام عليكم")
tokens

['ال', '##سلام', 'علي', '##كم']

In [8]:
subwords = tokenizer.convert_tokens_to_ids(tokens)
subwords

[445, 44831, 5468, 8155]

In [9]:
detokenized_text = tokenizer.convert_ids_to_tokens(subwords)
arabic_text = " ".join(detokenized_text).replace("##", "")
arabic_text

'ال سلام علي كم'

In [10]:
ids=tokenizer.convert_tokens_to_ids(tokens)
ids

[445, 44831, 5468, 8155]

In [11]:
ids=tokenizer.encode("السلام عليكم")
ids

[29756, 445, 44831, 5468, 8155, 29758]

In [12]:
tokenizer("السلام عليكم",return_tensors='pt')

{'input_ids': tensor([[29756,   445, 44831,  5468,  8155, 29758]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

In [13]:
tokenizer("السلام عليكم",return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[29756,   445, 44831,  5468,  8155, 29758]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [14]:
data=[".اريد السفر الى الخارج","هل تحب الكعك؟ "]
tokenizer(data)

{'input_ids': [[29756, 11, 12320, 445, 28351, 3001, 445, 44317, 29758], [29756, 893, 3319, 445, 1000, 8081, 83, 29758]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [15]:
model_inputs=tokenizer(data)

In [16]:
model_inputs=tokenizer(data,padding=True,truncation=True,return_tensors='pt')
model_inputs

{'input_ids': tensor([[29756,    11, 12320,   445, 28351,  3001,   445, 44317, 29758],
        [29756,   893,  3319,   445,  1000,  8081,    83, 29758, 29757]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0]])}

In [17]:
model_inputs=tokenizer(data,padding=True,truncation=True,return_tensors='tf')
model_inputs

{'input_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[29756,    11, 12320,   445, 28351,  3001,   445, 44317, 29758],
       [29756,   893,  3319,   445,  1000,  8081,    83, 29758, 29757]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}